### PR TITLE
Add Tasker Plug-in support

### PR DESCRIPTION
**Pull request by fgprodigal**

### CODE REVIEW

**Comment by Kr328** [comment]
Tasker support should **NOT** add to main app direct
Clash should provide common APIs, not just tasker

**Comment by fgprodigal** [comment]
> Tasker support should **NOT** add to main app direct
> 
> Clash should provide common APIs, not just tasker

So, where should I add Tasker support ?
I'm new into Android development

**Comment by Kr328** [comment]
just waiting for new APIs

**Comment by fgprodigal** [comment]
well, I can use this for my private currently 🤣

**Comment by gyj1109** [comment]
Any further progress here?

**Comment by goxofy** [comment]
> just waiting for new APIs

@Kr328 when？

**Pull request closed without merging**
